### ISSUE TITLE
Update METs data management handbook

### ISSUE THREAD

**Issue by mortenwh** [metno/data-management-handbook#104]
Before release of data.met.no, the DMH must be reviewed and updated.

**Comment by TomLav** [comment]
Should the url to WIGOS be fixed in [this](https://github.com/metno/data-management-handbook/blob/aabc212125520b7a4ab7aa902dda7b6ecbcd8e87/source/human-roles.adoc?plain=1#L39C305-L39C305) sentence?

The sentence refers to the WIGOS Levels of Data, but the url points at the WIGOS Sources of data.

The url for the Levels of Data is here: https://codes.wmo.int/wmdr/_LevelOfData

**Comment by mortenwh** [comment]
Fra Arnulf:

* Det hadde vært fint å få en liten oppfriskning på omfanget til dataforvaltning? Hvilke dataset er med og hvilke datasett er påvirket av dataforvaltningen.
* Vi er litt usikre på hvilke data som faller innenfor og utenfor dataforvaltningshåndboken.
* Og om data management regime i https://docs.google.com/document/d/1tmgYaAwsJ3sl0UpkdtKsHGc48fgD6tvplUGvMaerSDc/edit#heading=h.2afmg28 og dataforvaltningshåndboken er det samme.

**Comment by mortenwh** [comment]
consider merging the github and gitlab repo's as well

**Comment by mortenwh** [comment]
Need to review the latest version in comparison to the original.

**Comment by mortenwh** [comment]
* References have been deleted at some point - reintroduce..

**Comment by mortenwh** [comment]
* "Applicable and Reference Documents" needs to be reintroduced

**Comment by mortenwh** [comment]
* Appendix A needs to be updated

**Comment by mortenwh** [comment]
Add text about dataset granularity

**Comment by johtoblan** [comment]
Forfattere av DMH burde kanskje oppdateres/utvides?

Practical guides er fremdeles siste kap. skulle ikke denne flyttes frem? passer vel greit etter introduksjon?

Kap 2. §2: "For example, it will be described how the specification of datasets should be determined." Hvor/Når?

Listen i Kap 2. etter §2 er samme som i introduksjon (kap 1) bare mindre deskriptiv?

2.1 nevner at inspire skal bli amended i 2019. Dette har vel skjedd, hvis ikke må det ihvertfall oppdateres?

2.1§4: inkosistent bruk av THE WMO og bare WMO.

2.2 Hva er det teksten her prøver å kommunisere? "Traditionally, the data used have been transmitted on request from one data centre to another, and used in the specific processing chains that requested the data. The focus on reuse of data in various contexts has been missing." Missing fra hvor? Endres dette ved å følge DMH?

2.2 figur 1: finnes denne i pdf-versjon eller annen type vektor versjon?

2.3.1§1 "it must be possible to understand the meaning of the numerical value from the available machine-readable information" kan vel godt være "it must be possible to understand the meaning of the numerical value from the available machine-readable information" 

2.3.1: Er dette rett plass å ha definisjonen av Dataset? Burde ikke det komme tidligere i typ introduksjonen?

2.3.1§2: "e.g., clothing adapted to the forecast weather" skal vel være "e.g., clothing adapted to the forecasted weather"

2.3.2: litt inkosistent bruk av dataset og data jfr forrige avsnitt (Less advanced user bruker ikke dataset, men illustrasjoner av data?) er ikke LessAdvanced user en consumer user?

2.3.2.1 "Simple" har en rar konnotasjon, men dette er kanskje bare på norsk? Basic er kanskje bedre ord?

2.3.2.1.3 "• Can the event take place, or will the weather impeed it?" skal være "impede"

2.3.2.1.3:NOTE: Skjønner ikke første setning: "An advanced consumer may discover information pertaining a role as a simple consumer."

2.3.3. Er dette relevant i METs spesifikke DMH?

2.4.1 "A more detailed definition is provided in the Glossary of Terms." Glossary of Terms linker til definisjonen av glossary, ikke glossary of terms (side 64 vs 61)

2.4.1 principle 3. Hvis et parent dataset er et dataset, så vil den motstride prinsipp 3 her. "This (parent) dataset encompasses all datasets created by the model simulation such as, e.g., two NetCDF-CF files (child datasets) with different information content." skrives som om parent dataset ikke lengre er et dataset?

2.4.1.1§4 Dette er vel viktig nok til å være et eget prinsipp i 2.4.1 listen?

2.4.2.1 taxonomies brukes bare i dette delkap. det skal vel være ontologi? og ingen referanse for hverken controlled vocabularies eller "taxonomies" her.

Hva er en DBMS solution (side 21)

Hva er status på CAP metadata (side 22)

Side 22 (3.2.3§4) er det manglende referanser til ontology og vocabular. Skal dettte være for ALLE mentions eller bare første?

Hva er forskjellen på AD og RD?, noen referanser brukes ikke?

**Comment by mortenwh** [comment]
Hei Morten, 

I have finally had a chance to read through the DMH and it is a great piece of work. I like the current structure better, especially that the table of content is simplified in comparison to the previous version. 

I don't have much to add to the document now other than in chapter 6.2.1, the second paragraph: we have "Currently, agencies funding R&D (such as NFR and the EU) do not strictly require a DMP from the start of any project..". The NRC has introduced requirements for DMP for all projects that manage data and have received funding after jan 2018. 

I must also mention that the handbook has been a really useful reference for me in the SOFF project I am currently in. I may also have further comments next year as I will refer to the document more.

Kind regards
Elinah

**Comment by mortenwh** [comment]
> Practical guides er fremdeles siste kap. skulle ikke denne flyttes frem? passer vel greit etter introduksjon?

@johtoblan Jo, det har vært snakk om det. Men jeg er litt skeptisk, fordi det er mange henvisninger til "teori-delene" der, og noe kan forutsette en forståelse som må opparbeides gjennom å lese de andre kapitlene. Jeg har prøvd å gjøre innholdsfortegnelsen mer oversiktlig. Kan det fungere godt nok?

**Comment by mortenwh** [comment]
@johtoblan 

> 2.3.2: litt inkosistent bruk av dataset og data jfr forrige avsnitt (Less advanced user bruker ikke dataset, men illustrasjoner av data?) er ikke LessAdvanced user en consumer user?

Jeg ser ikke dette helt, men har prøvd med en oppdatering av brukerdefinisjonene. Var det det dere mente?

**Comment by mortenwh** [comment]
> Hva er status på CAP metadata (side 22)

??

**Comment by mortenwh** [comment]
@johtoblan - jeg har vært gjennom dette nå. Kan du se om det er ok?

**Comment by mortenwh** [comment]
Test py-mmd-tools API og legg inn bruksbeskrivelse i DMH
