### ISSUE TITLE
Documentation of ACDD metadata to MMD

### ISSUE THREAD

**Issue by niellaNina** [metno/data-management-handbook#2]
Documenting what to add to the netCDF files to be able to create correct MMD files.

**Comment by mortenwh** [comment]
This can be handled by CI and the new method proposed in https://github.com/metno/py-mmd-tools/issues/43. The CI runs on push to master but also needs to run once per day to pick up changes in metno/py-mmd-tools.

TODO:

- [ ] check CI and include daily runs if necessary
- [ ] add running of the new method to the CI system

**Comment by mortenwh** [comment]
I pushed directly to master to test this, and it works :) Closing this issue now.
