### ISSUE TITLE
Update and rewrite chapter 6

### ISSUE THREAD

**Issue by mortenwh** [metno/data-management-handbook#39]
- [x] Include "Global attributes that should be added to NetCDF-CF files" section (`acdd_elements.adoc`) in chapter 6
- [ ] Consider moving chapter 6 or parts of it to METs DMH version

**Comment by mortenwh** [comment]
I have tried to mirror contents of chapter 6 to the workflow list in the beginning of the chapter. I think I'm done until chapter 6.2. @TAlonglong - we should probably discuss how to continue...

**Comment by TAlonglong** [comment]
https://github.com/metno/data-management-handbook
