### ISSUE TITLE
Remove final documents from vc

### ISSUE THREAD

**Issue by ElodieFZ** [metno/data-management-handbook#47]
The final documents (pdf and html) should be removed from vc.
The images obtained from the diagrams too (some png in doc/images).

**Comment by mortenwh** [comment]
The files are added again by the ci - this was not that easy...

To do:

- [ ] update ci to not `git add` the html and pdf files 

- [ ] find a way to display the compiled html document

**Comment by ElodieFZ** [comment]
@mortenwh I think it's better now. The html and pdf end files are not part of the repo anymore. The html final document is available [here](https://metno.github.io/data-management-handbook/) and updated with CI. The bit I'm not very happy about is that this github page reads the info from a folder `docs` and I cannot change this name so it's not so similar to the `doc` folder containing the documentation files.

**Comment by mortenwh** [comment]
Hmm - ok.. Maybe we should change "our" name ("doc"), then.. But that can be done later, if necessary. I made a few updates, like force add to ensure the CI doesn't fail when there are no changes, plus I updated the author list etc. I also copied the images folder - was that necessary? Anyway, I'm closing this issue now. Thanks!
