### ISSUE TITLE
DMH: create asciidoc versions of the appendices to V1

### ISSUE THREAD

**Issue by niellaNina** [metno/data-management-handbook#7]
The following documents need to be created (glossary is already finished):​
List of Acronyms
Appendix A: List of Referenced Software or Service
Appendix B: Users of MET Norway’s Geodata	

the two last ones might be institute-specific and a template version must be made

Also: fix links to these documents in the introduction chapter.

**Comment by mortenwh** [comment]
Can you make a PR?
