### ISSUE TITLE
Handbook review feedback

### ISSUE THREAD

**Issue by IvanaH8** [metno/data-management-handbook#75]
Joint NILU and NIVA feedback on the handbook structure and contents, as agreed during the last workshop in August 2022. 

### Abstract
_‘This document describes general data management practices in line with the FAIR principles…’_ 
To do this we should add something about language and vocabulary (ref FAIR: I1, I2), PID schemes (EpiC, DOI, OrcID etc) (ref FAIR: F1, F3, A1, A1.1, A1.2, A2) and data license (ref FAIR: R1.1). This should be both general sections and institute specific sections. 
(Note: there is a small part about data license in section 6.2.2, this could be pushed higher.)

### Section 1
We think that large part of this section could be more concise in the main body of the handbook. Some specific information such as the user definitions (section 1.2.2) would be more suited as, for example, supplementary information in Appendix.

### Section 1.3.2. External data management requirements and forcing mechanisms specific to (insert organisation name here)
We are not sure what is the purpose of this section.

### Section 1.4
_‘The data management regime described in this DMH follows the Arctic Data centre model.’_
What does the Arctic Data Centre model mean? 

### Section 3
The chapter is not that understandable and is missing several parts ex. 3.2.1 Legacy etc. 

### Section 4.2
Is Table 3 intended to be under section 4.2.1 Current implementation at ...? Otherwise, the section 4.2.1 seems redundant as it would provide the same information as Table 3.

### Section 5.3.1.1
We are not sure what the organizational roles here refer to. There is a similar table in section 1.3.3 (Data management roles at ...). Is there a difference between the two?

### Section 6
This differs from institute to institute. For NILU, for example, none of the current subsections work as they are now. It could be more practical to, for instance, direct the reader to the individual institutes' own handbooks here instead.

### NIVA's last minute comment
In general, the handbook is quite detailed but we feel that it could benefit from a chapter/subsection about FAIR principles and how these are/will be addressed. The chapter 5 (Data Governance) could then be included here as well.

**Comment by mortenwh** [comment]
Moved to https://github.com/S-ENDA/data-management-handbook/issues/1
