### ISSUE TITLE
CORS problems when doing http requests

### ISSUE THREAD

**Issue by HCNenseth** [metno/data-management-handbook#83]
When using React and axios(library) to send http post resquests I get CORS problems.
No problems using cURL.

**Comment by mortenwh** [comment]
![Screenshot from 2022-11-21 14-28-12](https://user-images.githubusercontent.com/109061/203067371-690d2298-c29d-4624-93ad-d53c2f4bd457.png)

**Comment by mortenwh** [comment]
Han brukte samme fremgangsmåte som vi har beskrevet i dataforvaltningshåndboken (https://metno.github.io/data-management-handbook/#_advanced_geographical_search). Eksempelet der fungerer når jeg kjører fra kommandolinjen. Se skjermdump for feilmelding i react/axios. Er dette noe som må gjøres i kubernetes?

**Comment by cskarby** [comment]
I believe the best place for fixing this is within the application server, as javascript access to pycsw is probably desired regardless of runtime environment. However it is possible to [configure ingress-nginx to add CORS-headers](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#enable-cors), but this is specific to ingress-nginx, and not a general fix for kubernetes.

**Comment by johtoblan** [comment]
Will check with people more knowledgeable  about CORS before implementing in Staging and Prod
