### ISSUE TITLE
Practical guides chapter - specific by institute?

### ISSUE THREAD

**Issue by vivigirardin** [metno/data-management-handbook#85]
NIVA's suggestion is to let each institute create their own guide and link it to the chapter because:

-	This is the chapter that will be least likely to fit all. By each institute having the flexibility to create their own guides, there is a greater chance that the DMH will continue to be used and updated in the future.
-	Instead of trying to fit all institutes in a box, we would continue to learn from each other.
-	Internal guides could be included, increasing the usability of the handbook beyond S-ENDA.

**Let’s discuss!**

**Comment by vivigirardin** [comment]
Once again, I can't assign @BenCretois.

**Comment by TAlonglong** [comment]
He is invited, but has not accepted the invitation. I can't do anything more than resend the invitation. He has to accept himself.

**Comment by lisemurberg** [comment]
I agree that this whole chapter should be a institute specific chapter, but I think we should have some headlines for elements that we wish that all institute includes in the practical guide. 

So 6.1. Create a Data Management Plan (DMP) should be included, but the sub-chapters 6.1.1. and 6.1.2. are filled inn for each institute. 

In total it could be something like: 

- Create a Data Management Plan
- Submitting data to {Fill inn specific} (NILU/EBAS/NetCDF/MET etc, whatever the institute wish). 
- Accessing data for users
- > Web portals
- > Other methods: THREDDS, Metadata search, OpenSearch etc.
- Vocabulary(?) 

Each institute can of course add more chapters if they wish, but I think we should have a minimum that each institute should fill in.

**Comment by mortenwh** [comment]
Will be followed up in https://github.com/S-ENDA/data-management-handbook
