### ISSUE TITLE
New version of py-mmd-tools broke the DMH actions...

### ISSUE THREAD

**Issue by mortenwh** [metno/data-management-handbook#91]
- [ ] DMH is not compiling now, because the yaml2qadoc script was moved
- [ ] the issue is most likely on gitlab as well

**Comment by johtoblan** [comment]
The script is installed as an entry-point. So you can instead run `yaml2qadoc` directly instead of ``./yaml2adoc.py``

**Comment by johtoblan** [comment]
Nevermind, the package is only pulled, then run. I will test and update

**Comment by johtoblan** [comment]
Package was pulled, and requirements.txt was installed. Updated the docker in the PR to install properly, and then using the entry points. See #92
