### ISSUE TITLE
Document how a data-producer can verify that the data they have ingested into the event queue is present in the csw or data-test endpoint.

### ISSUE THREAD

**Issue by johtoblan** [metno/data-management-handbook#93]
Is the current documentation outdated or wrong?

**Comment by shamlymajeed** [comment]
Should this be added in `specialized_practical_guidance_template.adoc` in dmh ?

**Comment by mortenwh** [comment]
Put it at the end of the file `register_context.adoc`, under a new headline:

```
[[ test-MMD-ingested ]]
===== Check that the MMD file has been added
```

**Comment by mortenwh** [comment]
It seems the PR here was never reviewed..? Also, the PRs need to be connected to their respective issues in order to make it easier to keep the overview. And branches should be named as issue93_check_ingested in this case.

I will check the documentation and give further comments.

**Comment by mortenwh** [comment]
1. The heading of the new section is mis-typed, so it doesn't compile correctly. This needs to be fixed.
2. "where * should be either dev or staging and can specify the title of the dataset in a date or within a given time span" - it is unclear what you mean by the last part of the sentence (from "and can specify"). Please improve the text.
3. The rest of the text is incomplete and missing punctuation marks. Please improve.
4. @magnarem also added a comment in the PR - please add that tip as another way to check.
